chmod 755 claude_monet
chmod u=rwx,g=rx,o= claude_monet/pastry_station
chmod 750 claude_monet/pastry_station/oven
chmod u=rw,g=r,o= claude_monet/pastry_station/oven/croissant_plan
chmod 640 claude_monet/pastry_station/oven/millefeuille_plan
chmod u=rwx,g=rx,o= claude_monet/pastry_station/cold_room
chmod 600 claude_monet/pastry_station/cold_room/cream_note
chmod u=rw,g=r,o=r claude_monet/pastry_station/dessert_menu
chmod 755 claude_monet/hall
chmod u=rw,g=rw,o=r claude_monet/hall/banquet_orders
chmod 644 claude_monet/hall/guest_wishes
chmod u=rwx,g=rx,o= claude_monet/office
chmod 640 claude_monet/office/barinov_comment
chmod 750 louis_room
chmod u=r,g=r,o= louis_room/louis_diary
chmod 644 louis_room/work_schedule
chmod u=rwx,g=,o= empty_boxes
chmod u=rw,g=r,o=r morning_order
